### ISSUE TITLE
Template to start

### ISSUE THREAD

**Issue by alexanmtz** [danilocerqueira/quantofaltaprocarnaval.com.br#1]
Let's use this one?
[https://codepen.io/alexanmtz/full/KRXGze/](https://codepen.io/alexanmtz/full/KRXGze/)

**Comment by danilocerqueira** [comment]
I just loved the moving papers

Let's use it!

**Comment by alexanmtz** [comment]
Go to your project, and follow this path to activate the Github pages in your account.
![github-page-activation](https://user-images.githubusercontent.com/88840/39715075-5095a980-522c-11e8-87db-1250e8b76dd6.gif)

So after you should see a [http://danilocerqueira.github.io/quantofaltaparaocarnaval.com.br](http://danilocerqueira.github.io/quantofaltaparaocarnaval.com.br) a welcome page.

**Comment by alexanmtz** [comment]
Para registrar no [registro.br](registro.br): [https://github.com/orige/githubpages.registro.br](https://github.com/orige/githubpages.registro.br)

**Comment by danilocerqueira** [comment]
Ow, when it's time, let's set the Date for the Next Carnaval to 6 pm of March 1th

**Comment by alexanmtz** [comment]
it's there: [http://www.quantofaltaprocarnaval.com.br/](http://www.quantofaltaprocarnaval.com.br/)

Now let's display the countdown (It's the finaaaaaal countdoooown!)

**Comment by alexanmtz** [comment]
Updated!

![pageshot of quanto falta para o carnaval_ 2018-05-02-2223 54](https://user-images.githubusercontent.com/88840/40081610-c84ad550-588e-11e8-97a8-5e9e9247e3db.png)

**Comment by alexanmtz** [comment]
I think we have a version 🎉
