### ISSUE TITLE
Display on mobile

### ISSUE THREAD

**Issue by alexanmtz** [danilocerqueira/quantofaltaprocarnaval.com.br#8]
After we had the random images on home page, we need to adapt the background on mobile:
![pageshot of carnaval 3 2018-07-01-2054 21](https://user-images.githubusercontent.com/88840/42470329-67d63794-83ba-11e8-9b76-cef5f9eb9a5b.png)

On desktop is great, we are using the `background-size` property to cover but on mobile the different orientation make the images not fit correctly. We need a solution for this

**Comment by alexanmtz** [comment]
https://gitpay.me/#/task/50

**Comment by danilocerqueira** [comment]
I had a simple idea to try to solve this:

We can have two carnival picture folders:
-Portrait 
-Landscape

So, before choosing which folder the system will randomly select an image, it will analyze the screen that the image will be shown.

So before choosing which folder the system will randomly select an image, we have to analyze the screen that the site will be displayed. If it is more horizontal (like a laptop), we choose from Landscape, if it is more vertical (like the mobile), an image will be chosen from the Portrait folder.

**Comment by alexanmtz** [comment]
https://gitpay.me/#/task/50

**Comment by eriksonJAguiar** [comment]
@alexanmtz fiz a correção no display e enviei o pull request !

**Comment by alexanmtz** [comment]
@eriksonJAguiar dá uma olhada no comentário do @danilocerqueira sobre uma solução. Na verdade a solução atual com o cover funciona muito bem em desktop, então teremos que mantê-lo e quando for mobile ele carregar outro set de imagens (assim teríamos portrait e landscape)

Então acredito que teríamos que detectar por js antes o tamanho para direcionar as imagens para folders diferentes.

Mas poderíamos testar primeiro antes de uma solução mais elaborada de repente ter uma media-query que se for mobile anula esta propriedade, como você fez no pull-request, mas somente no mobile. A solução desktop continua como está.

**Comment by eriksonJAguiar** [comment]
@alexanmtz fiz dessa forma:

@media  (max-width: 1024px) and (orientation:portrait){
    body {
       min-height: 100vh;
       display: flex;
       justify-content: center;
       align-items: center;
       font-family: "Quicksand", sans-serif;
       font-size: 16px;
       background-size: cover;
       background-repeat: no-repeat;
   }
}

body {
    display: flex;
    justify-content: center;
    align-items: center;
    font-family: "Quicksand", sans-serif;
    font-size: 16px;
    background-size: cover;
}

O que acha ?

**Comment by alexanmtz** [comment]
Ficou show @eriksonJAguiar, pode atualizar o PR?

**Comment by eriksonJAguiar** [comment]
@alexanmtz  pull request atualizado !!

**Comment by alexanmtz** [comment]
@danilocerqueira , eu aprovei as mudanças, dá uma olhada 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by alexanmtz** [comment]
I added a support for different sizes that now is possible to setup in the component file.

@danilocerqueira , now we have:

`if(dimensions.width < 360) { // mobile images`

Followed by the list in mobile and the else cause show the non mobile files, you can now organize the list. what we can do is renaming images for mobile with `mobile`  suffix and put on the list
